# Generated by Django 4.2.1 on 2024-04-17 17:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bakery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bakery_name', models.CharField(max_length=255)),
                ('image', models.ImageField(default=None, null=True, upload_to='bakery_images')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bakery',
                'verbose_name_plural': 'Bakeries',
                'db_table': 'bakery_name',
                'db_table_comment': 'Table with all bakeries',
            },
        ),
        migrations.CreateModel(
            name='BakeryTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bakery_type', models.CharField(max_length=255)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bakery Type',
                'verbose_name_plural': 'Bakery Types',
                'db_table': 'bakery_types',
                'db_table_comment': 'Table with all bakery types',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_of_placement', models.DateTimeField(auto_now_add=True)),
                ('date_of_delivery', models.DateTimeField(default=None, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('customer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customers')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'orders',
                'ordering': ['-date_of_placement'],
            },
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('bakery_id', models.ManyToManyField(to='gallery.bakery')),
            ],
            options={
                'verbose_name': 'Ingredient',
                'verbose_name_plural': 'Ingredients',
                'db_table': 'ingredients',
                'db_table_comment': 'Table with all ingredients',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('bakery_id', models.ManyToManyField(to='gallery.bakery')),
                ('order_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gallery.order')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'db_table': 'order_items',
                'db_table_comment': 'All items within specified order',
            },
        ),
        migrations.CreateModel(
            name='BakeryDescriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(unique=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('bakery_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gallery.bakery')),
            ],
            options={
                'verbose_name': 'Bakery Description',
                'verbose_name_plural': 'Bakery Descriptions',
                'db_table': 'bakery_description',
                'db_table_comment': 'Table with all bakery descriptions',
            },
        ),
        migrations.AddField(
            model_name='bakery',
            name='bakery_type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.bakerytypes'),
        ),
    ]
