# Generated by Django 5.0.4 on 2024-06-21 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('gallery', '0001_initial'), ('gallery', '0002_alter_ingredients_name'), ('gallery', '0003_alter_bakerytypes_bakery_type'), ('gallery', '0004_alter_bakery_bakery_name')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bakery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bakery_name', models.CharField(max_length=255)),
                ('image', models.ImageField(default=None, null=True, upload_to='bakery_images')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bakery',
                'verbose_name_plural': 'Bakeries',
                'db_table': 'bakery',
                'db_table_comment': 'Table with all bakeries',
            },
        ),
        migrations.CreateModel(
            name='BakeryTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('bakery_type', models.CharField(blank=True, db_index=True, default='', max_length=255, null=True, unique=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bakery Type',
                'verbose_name_plural': 'Bakery Types',
                'db_table': 'bakery_types',
                'db_table_comment': 'Table with all bakery types',
            },
        ),
        migrations.CreateModel(
            name='BakeryDescriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(unique=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('bakery_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gallery.bakery')),
            ],
            options={
                'verbose_name': 'Bakery Description',
                'verbose_name_plural': 'Bakery Descriptions',
                'db_table': 'bakery_description',
                'db_table_comment': 'Table with all bakery descriptions',
            },
        ),
        migrations.AddField(
            model_name='bakery',
            name='bakery_type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.bakerytypes'),
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('description', models.TextField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('bakery_id', models.ManyToManyField(to='gallery.bakery')),
            ],
            options={
                'verbose_name': 'Ingredient',
                'verbose_name_plural': 'Ingredients',
                'db_table': 'ingredients',
                'db_table_comment': 'Table with all ingredients',
            },
        ),
        migrations.AlterField(
            model_name='bakery',
            name='bakery_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
