# Generated by Django 4.2.1 on 2024-04-17 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bakery',
            table='bakery',
        ),
    ]
