# Generated by Django 5.0.4 on 2024-06-21 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_ingredients_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bakerytypes',
            name='bakery_type',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, null=True, unique=True),
        ),
    ]
