# Generated by Django 5.0.4 on 2024-05-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_remove_order_customer_id_delete_cart_delete_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakerytypes',
            name='depth',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bakerytypes',
            name='numchild',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bakerytypes',
            name='path',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='bakerytypes',
            name='bakery_type',
            field=models.CharField(blank=True, default='', max_length=255, null=True, unique=True),
        ),
    ]
