# Generated by Django 5.0.4 on 2024-06-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_bakerytypes_bakery_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bakery',
            name='bakery_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
