# Generated by Django 5.0.4 on 2024-05-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_bakerytypes_depth_bakerytypes_numchild_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bakerytypes',
            name='depth',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='bakerytypes',
            name='path',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
