# Generated by Django 5.0.4 on 2024-12-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_rename_bakerytypes_bakerytype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bakery',
            name='bakery_name',
            field=models.TextField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='bakerytype',
            name='bakery_type',
            field=models.TextField(blank=True, db_index=True, default='', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.TextField(db_index=True, max_length=50),
        ),
    ]
