# Generated by Django 5.0.4 on 2024-12-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_alter_bakery_bakery_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakery',
            name='description',
            field=models.TextField(null=True, unique=True),
        ),
    ]
