# Generated by Django 5.0.4 on 2024-12-21 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_bakery_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BakeryDescriptions',
        ),
    ]
