# Generated by Django 5.0.4 on 2024-05-17 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='mobile_number',
            field=models.CharField(help_text='Use valid number format of 10 digits', max_length=10, null=True, unique=True),
        ),
    ]
