# Generated by Django 5.0.4 on 2024-05-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0002_alter_customerprofile_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='mobile_number',
            field=models.CharField(default=None, help_text='Use valid number 10 digits', max_length=10, null=True, unique=True),
        ),
    ]
