# Generated by Django 5.0.4 on 2024-11-02 10:11

import custom_user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0005_alter_user_managers_alter_user_mobile_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='mobile_number',
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(blank=True, help_text='Use valid number 10 digits', max_length=10, null=True, validators=[custom_user.models.mobile_number_validator]),
        ),
    ]
