# Generated by Django 4.2.1 on 2024-04-17 17:02

import customers.managers.customers_manager
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mobile_number', models.CharField(help_text='Use valid number format of 10 digits', max_length=10, unique=True)),
                ('email', models.EmailField(help_text='Use valid email format', max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'customers',
                'db_table_comment': 'Customer base model, created with most necessary data to place an order',
                'ordering': ['id'],
            },
            managers=[
                ('objects', customers.managers.customers_manager.CustomerManager()),
            ],
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=50)),
                ('profile_img', models.ImageField(default=None, null=True, upload_to='customer_pictures/')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('customer_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customers.customers')),
            ],
            options={
                'verbose_name': 'Customer Profile',
                'verbose_name_plural': 'Customer Profiles',
                'db_table': 'customer_profile',
                'db_table_comment': 'Customers profile with additional data, created when user completes registration.',
                'ordering': ['pk'],
                'unique_together': {('first_name', 'second_name', 'date_of_birth')},
                'index_together': {('first_name', 'second_name')},
            },
        ),
    ]
