# Generated by Django 5.0.4 on 2024-04-20 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customerprofile',
            new_name='customer_pr_first_n_2cc879_idx',
            old_fields=('first_name', 'second_name'),
        ),
    ]
