# Generated by Django 5.0.4 on 2024-04-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_rename_customerprofile_first_name_second_name_customer_pr_first_n_2cc879_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customerprofile',
            name='customer_pr_first_n_2cc879_idx',
        ),
        migrations.RenameField(
            model_name='customerprofile',
            old_name='second_name',
            new_name='last_name',
        ),
        migrations.AlterUniqueTogether(
            name='customerprofile',
            unique_together={('first_name', 'last_name', 'date_of_birth')},
        ),
        migrations.AddIndex(
            model_name='customerprofile',
            index=models.Index(fields=['first_name', 'last_name'], name='customer_pr_first_n_3cae83_idx'),
        ),
    ]
