# Generated by Django 5.0.4 on 2024-09-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('c', 'Confirmed'), ('d', 'Delivered'), ('p', 'Pending'), ('rcd', 'Received'), ('r', 'Rejected'), ('a', 'Archived'), ('s', 'Suspended'), ('b', 'Basket'), ('prcg', 'Processing'), ('shpg', 'Shipping')], default='b', max_length=4),
        ),
    ]
