# Generated by Django 5.0.4 on 2024-12-21 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0005_alter_cartitems_order_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bakery_name', models.CharField(max_length=250)),
                ('quantity', models.IntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_item', to='shopping_cart.order')),
            ],
            options={
                'verbose_name': 'Cart Item',
                'verbose_name_plural': 'Cart Items',
                'db_table': 'cart_item',
                'db_table_comment': 'All items within specified order',
            },
        ),
        migrations.DeleteModel(
            name='CartItems',
        ),
    ]
