# Generated by Django 5.0.4 on 2024-12-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0006_cartitem_delete_cartitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='bakery_name',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.TextField(choices=[('c', 'Confirmed'), ('d', 'Delivered'), ('p', 'Pending'), ('rcd', 'Received'), ('r', 'Rejected'), ('a', 'Archived'), ('s', 'Suspended'), ('b', 'Basket'), ('prcg', 'Processing'), ('shpd', 'Shipping')], default='b', max_length=4),
        ),
    ]
