# Generated by Django 5.0.4 on 2024-12-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0007_alter_cartitem_bakery_name_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='price_per_item',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
